import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next Portfolio Studio",
  description: "Generated by create next app",
};

function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

export default Layout;
